

CREATE TABLE CAR(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT
BY 1)
, LICENSE_PLATE VARCHAR(20) NOT NULL
, MANUFACTURER VARCHAR(20) NOT NULL
, MANUFACTURE_DATE DATE NOT NULL
, AGE INT NOT NULL DEFAULT 0
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE (LICENSE_PLATE)
, PRIMARY KEY (ID)
);
