DROP TABLE CONTACT;
DROP TABLE  CONTACT_HOBBY_DETAIL;
DROP TABLE  CONTACT_TEL_DETAIL;
DROP TABLE  HOBBY;
DROP TABLE CONTACT_AUDIT;
DROP TABLE CONTACT_AUDIT_H;
DROP TABLE REVINFO;


CREATE ROLE aaa;
CREATE ROLE bbb;

CALL SYSCS_UTIL.SYSCS_CREATE_USER('aaa', 'aaa');
CALL SYSCS_UTIL.SYSCS_CREATE_USER('bbb', 'bbb');

CREATE SCHEMA prospringa AUTHORIZATION aaa;
CREATE TABLE prospringa.CONTACT (
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT
BY 1)
, FIRST_NAME VARCHAR(60) NOT NULL
, LAST_NAME VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE (FIRST_NAME, LAST_NAME)
, PRIMARY KEY (ID)
) ;


CREATE SCHEMA prospringb AUTHORIZATION bbb;
CREATE TABLE prospringb.CONTACT (
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT
BY 1)
, FIRST_NAME VARCHAR(60) NOT NULL
, LAST_NAME VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE (FIRST_NAME, LAST_NAME)
, PRIMARY KEY (ID)
) ;




CREATE TABLE CONTACT (
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT
BY 1)
, FIRST_NA�E VARCHAR(60) NOT NULL
, LAST_NA�E VARCHAR(40) NOT NULL
, BIRTH_DATE DATE
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE (FIRST_NA�E, LAST_NA�E)
, PRIMARY KEY (ID)
) ;

CREATE TABLE HOBBY (
HOBBY_ID VARCHAR(20) NOT NULL
, PRIMARY KEY (HOBBY_ID)
);

CREATE TABLE CONTACT_TEL_DETAIL(
ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT
BY 1)
, CONTACT_ID INT NOT NULL
, TEL_TYPE VARCHAR (20) NOT NULL
, TEL_NUMBER VARCHAR (20) NOT NULL
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE (CONTACT_ID, TEL_TYPE)
, PRIMARY KEY (ID)
, CONSTRAINT FK_CONTACT_TEL_DETAIL_1 FOREIGN KEY (CONTACT_ID)
REFERENCES CONTACT (ID)
) ;

CREATE TABLE CONTACT_HOBBY_DETAIL (
CONTACT_ID INT NOT NULL
, HOBBY_ID VARCHAR(20) NOT NULL
, PRIMARY KEY (CONTACT_ID, HOBBY_ID)
, CONSTRAINT FK_CONTACT_����Y_DETAIL_1 FOREIGN KEY (CONTACT_ID)
REFERENCES CONTACT (ID) ON DELETE CASCADE
, CONSTRAINT FK_CONTACT_HOBBY_DETAIL_2 FOREIGN KEY (HOBBY_ID)
REFERENCES HOBBY (HOBBY_ID)
) ;

insert into contact (FIRST_NA�E, LAST_NA�E, BIRTH_DATE)
values ('Chris', 'Schaefer', '1981-05-03');
insert into contact (FIRST_NA�E, LAST_NA�E, BIRTH_DATE)
values ('Scott', 'Tiger', '1990-11-02');
insert into contact (FIRST_NA�E, LAST_NA�E, BIRTH_DATE)
values ('John', 'Smith', '1964-02-28');
insert into contact_tel_detail (CONTACT_ID, TEL_TYPE, TEL_NUMBER)
values ( 1, 'Mobile', '1234567890');
insert into contact_tel_detail (CONTACT_ID, TEL_TYPE, TEL_NUMBER)
values (1, 'Home', '1234567890');
insert into contact_tel_detail (CONTACT_ID, TEL_TYPE, TEL_NUMBER)
values (2, 'Home', '1234567890');
insert into hobby (HOBBY_ID) values ( 'Swimming' ) ;
insert into hobby (HOBBY_ID) values ( 'Jogging') ;
insert into hobby (HOBBY_ID) values ('Programming');
insert into hobby (HOBBY_ID) values ( 'Movies');
insert into hobby (HOBBY_ID) values ( 'Reading' ) ;
insert into contact_hobby_detail(CONTACT_ID, HOBBY_ID) values (1, 'Swimming');
insert into contact_hobby_detail(CONTACT_ID, HOBBY_ID) values (1, 'Movies');
insert into contact_hobby_detail(CONTACT_ID, HOBBY_ID) values (2, 'Swimming');